OD-596 [Feature] Added app version number validation
Fliplet/fliplet-widget-app-submission pull request #148
Opened 2021-11-11 09:16 UTC by skrupnyk

@romanyosyfiv

OD-596 https://weboo.atlassian.net/browse/OD-596

## Description
Added app version number validation. The user will not be able to submit the form if the version number is in the wrong format or is less than a pre-existing version number.

## Screenshots/screencasts
https://storyxpress.co/video/kvuqi9hn52bid7iwn

## Backward compatibility
This change is fully backward compatible.

## Reviewers
@upplabs-alex-levchenko

2021-12-09 21:45 UTC, tonytlwu requested changes

2021-12-10 10:38 UTC, skrupnyk commented on js/interface.js
> +        if (a > b) {
> What happens if `a` and `b` are the same?

In this case, the cycle will end and the same error message will appear. You can see it below in the code.

2021-12-10 10:39 UTC, skrupnyk commented on js/interface.js
> +      var previosVersion = $el.data('validation-version-number');
> Keeping terminologies consistent.

fixed

2021-12-10 10:39 UTC, skrupnyk commented on js/interface.js
> +          $el.attr('data-validation-version-number-error', 'Please make sure the version number is higher than ' + $el.data('validation-version-number'));
> You shouldn't need to read the value again.

fixed

2021-12-14 12:32 UTC, tonytlwu approved these changes
@romanyosyfiv @inna-bieshulia This is ready for testing

Risk: Medium
Affected: Studio users submitting iOS app builds
Verify: App builds are submitted with the correct version numbers

Squash and merge: Use PR title

2021-12-28 09:21 UTC, merged